---
- name: AWS server instance setup
  hosts: tag_Perf_JMETER
#  connection: local
  gather_facts: False  
  become: true
  become_method: sudo
  tasks:
#    - ping:
      
    - name: Install Python
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - name: Wait for python directory creation  
      wait_for:
        path: /usr/bin/python

    - name: Update APT
      apt:
        update_cache: yes
    
    - name: Upgrade APT
      apt:
        upgrade: yes

    - name: Install JDK
      apt:
        name: default-jre

    - name: Set JVM memory size
      raw: export _JAVA_OPTIONS="-Xms512m -Xmx2096m"

#   - pause:
#          seconds: 5

    - name: jmeter | Download jmeter
      get_url:
        url: https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-3.3.tgz
        dest: /home/ubuntu/
      become: true
      become_user: ubuntu
      register: jmeter_download 

    - name: Extract Jmeter
      unarchive:
        src: /home/ubuntu/apache-jmeter-3.3.tgz
        dest: /home/ubuntu/
        mode: u+xrw
        remote_src: yes  
      become: true
      become_user: ubuntu

    - name: Set JVM size
      shell: echo _JAVA_OPTIONS is $_JAVA_OPTIONS
      environment:
        _JAVA_OPTIONS: "-Xms512m -Xmx2096m"
      register: shellout
 #     shell: export _JAVA_OPTIONS='-Xms512m -Xmx2096m'
      become: true
      become_user: ubuntu
    - debug: var=shellout

#    - pause: 
#        seconds: 5

    - name: Start Jmeter
      shell: nohup /home/ubuntu/apache-jmeter-3.3/bin/jmeter-server &
      become: true
      become_user: ubuntu
