---
- name: AWS server instance setup
  hosts: tag_Perf_PERF_SLAVE
  connection: local
  gather_facts: False  

  tasks:
    - name: Terminate JMeter Slave Server(s)
      ec2:
        region: "us-east-1"
        instance_ids: '{{ ec2_id }}'
        state: absent
        wait: yes
      register: vpc
      ignore_errors: no

- name: AWS server instance setup
  hosts: tag_Perf_PERF_JMASTER
  connection: local
  gather_facts: False

  tasks:
    - name: Terminate JMeter Master Server(s)
      ec2:
        region: "us-east-1"
        instance_ids: '{{ ec2_id }}'
        state: absent
        wait: yes
      register: vpc
      ignore_errors: no

    - name: Set network facts to destroy VPC
      set_fact:
        n_vpc_id: "{{ ec2_vpc_id }}"
 #       n_security_grp: "{{ ec2_security_group_ids }}"
        n_key_name: "{{ ec2_key_name }}"
 
    - name: Terminate route table
      ec2_vpc_route_table:
        vpc_id: "{{ n_vpc_id }}"
        region: "us-east-1"
        tags:
          Name: "J_ROUTE" 
        state: absent 


    - name: terminate subnet
      ec2_vpc_subnet:
        vpc_id: "{{ n_vpc_id }}"
        region: "us-east-1"
        cidr: "172.30.1.0/24"
        tags:
          Name: "J_SUBNET"
        state: absent

    - name: Terminate gateway
      ec2_vpc_igw:
        vpc_id: "{{ n_vpc_id }}"
        region: "us-east-1"
        tags:
          Name: "J_IGW"
        state: absent

#    - name: "List groups"
#      debug:
#        var: "{{ ec2_security_group_ids }}"

    - name: "Delete group ids"
      ec2_group:
        name: "JMeter_default_Grp"
#        group_id: "{{ ec2_security_group_ids }}"
        region: "us-east-1"
        state: absent
#        tags:
#          Sec: "JMeter_Sec_Grp"

    - name: "Delete group ids"
      ec2_group:
        name: "JMeter_Security_Grp"
#        group_id: "{{ ec2_security_group_ids }}"
        region: "us-east-1"
        state: absent
#        tags:
#          Sec: "JMeter_Sec_Grp"

    - name: Terminate VPC
      ec2_vpc_net:
        name: "JMeter_VPC"
        region: "us-east-1"
        cidr_block: "172.30.0.0/16" 
        state: absent

#    - name: "Delete group ids"
#      ec2_group:
#        group_id: "{{ n_security_grp }}"
#        region: "us-east-1"
#        state: absent

    - name: Delete EC2 Key
      ec2_key:
        name: "{{ n_key_name }}"
        region: "us-east-1"
        state: absent


   


