---
- name: AWS server instance setup
  hosts: tag_Perf_PERF_SLAVE
  gather_facts: False  
  become: true
  become_method: sudo

  tasks:
      
    - name: Install Python
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - name: Wait for python directory creation  
      wait_for:
        path: /usr/bin/python

    - name: Update APT
      apt:
        update_cache: yes
    
    - name: Upgrade APT
      apt:
        upgrade: dist

    - name: Install JDK
      apt:
        name: default-jre

- name: Setup JMeter
  hosts: tag_Perf_PERF_SLAVE
  gather_facts: False
  become_user: ubuntu
 
  tasks:
 
    - name: jmeter | Download jmeter
      get_url:
        url: https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-3.3.tgz
        dest: /home/ubuntu/
#      become: false
#      become_user: ubuntu
      register: jmeter_download 

    - name: Extract Jmeter
      unarchive:
        src: /home/ubuntu/apache-jmeter-3.3.tgz
        dest: /home/ubuntu/
        mode: u+xrw
        remote_src: yes  
 #     become: false
#      become_user: ubuntu

#    - name: Set JVM size
#      shell: echo _JAVA_OPTIONS is $_JAVA_OPTIONS
#      environment:
#        _JAVA_OPTIONS: "-Xms512m -Xmx2096m"
#      shell: "export _JAVA_OPTIONS='-Xms512m -Xmx2096m'"
#      become: false
#      become_user: ubuntu
      register: shellout

    - name: Debug Shellout
      debug:
        var: shellout
 
    - name: Start Jmeter
      shell: |
        cd apache-jmeter-3.3/bin
        nohup ./jmeter-server & > nohup.out
        sleep 5 
#        until stat ./nohup.out 2>/dev/null; do echo Waiting...; sleep 1; done
#      become: false
#      become_user: ubuntu
